#!/bin/bash


# opening the most recet .gpx file from download folder
cd /home/shef/Downloads/
gpx_file=`ls -t *.gpx | head -1`
file_text=`cat $gpx_file`
line_time=`grep time $file_text`
echo $line_line


# TO DO
# set upp and lower bounds for time so that dont have to over so many itterations in while loop-



# get into folder with pictures and do all needed calculations over them
# get a times stamp, convert it to UTC then find closeset time in .gpx file
# need UTC time because .gpx file time in UTC format

cd /home/shef/Desktop/pics_fuji/scripts/input_gps/
for picture in *;
do
	# get hour and minutes from current picture
	echo $picture
	time=`exiftool -time:DateTimeOriginal -s $picture | awk '{print$4}'`
	hour=`echo $time | cut -c 1-2`
	minutes=`echo $time | cut -c 4-5`

	hour=`expr $hour + 4`
	echo $hour

	# TO DO
	# format time in case hours is more thand 24
	# there is no 24 hour in .gpx file

	time_string="${hour}:${minutes}.000Z"
	
	echo $time_string
	

done

